package net.swordie.ms.handlers.header;

import java.util.Arrays;
import java.util.List;

/**
 * Created on 2/18/2017.
 */
public enum OutHeader {

    // CLogin::OnPacket : v176 -> 00ADA117
    CHECK_PASSWORD_RESULT(0),
    WORLD_INFORMATION(1),
    LATEST_CONNECTED_WORLD(2),
    RECOMMENDED_WORLD_MESSAGE(3),
    SET_CLIENT_KEY(4),
    SET_PHYSICAL_WORLD_ID(5),
    SELECT_WORLD_RESULT(6),
    SELECT_CHARACTER_RESULT(7),
    ACCOUNT_INFO_RESULT(8),
    CREATE_MAPLE_ACCOUNT_RESULT(9),
    CHECK_DUPLICATED_ID_RESULT(10),
    CREATE_NEW_CHARACTER_RESULT(11),
    DELETE_CHARACTER_RESULT(12),
    RESERVED_DELETE_CHARACTER_RESULT(13),
    RESERVED_DELETE_CHARACTER_CANCEL_RESULT(14),
    RENAME_CHARACTER_RESULT(15),
    SET_CHARACTER_ID(16),
    MIGRATE_COMMAND(17),
    ALIVE_REQ(18),
    PING_CHECK_RESULT(19),
    AUTHEN_CODE_CHANGED(20),
    AUTHEN_MESSAGE(21),
    SECURITY_PACKET(22),
    PRIVATE_SERVER_PACKET_SEND(23),
    //
    //
    CHECK_SPW_EXIST_RESPONSE(26),
    CHANGE_SPW_RESULT(27),
    //
    //
    ALBA_RESULT(30),
    //
    //
    SET_AUTO_SELECTED_WORLD(33),
    WORLD_INFO_FOR_SHINING_RESULT(34),
    CHOOSE_GENDER(35),
    GENDER_SET(36),
    HACKSHIELD_REQUEST(37),
    FORCED_CHANGE_CHAR_NAME(38),
    FORCED_CHANGE_CHAR_NAME_NOTICE(39),
    SERVERSTATUS(40),
    MAPLOGIN(41),
    //
    //
    //
    //
    SET_HOT_FIX(46),
    //
    SERVER_STATUS(),
    //
    INIT_OPCODE_ENCRYPTION(),
    //
    //
    //
    //
    //
    //
    AUTH_SERVER(),

    // CChatSocket::ProcessPacket
    CHAT_LOGIN_RESULT(1),
    CHAT_LOGOUT_RESULT(11),
    CHAT_ALIVE_REQ(13),
    CHAT_ENTER_GUILD_CHAT_ROOM_RESULT(15),
    CHAT_GUILD_CHAT_MESSAGE(18),
    CHAT_FRIEND_CHAT_MESSAGE(19),
    CHAT_BLOCK_GUILD_FRIEND_CHAT(28),

    // CMapLoadable::OnPacket
    SET_BACK_EFFECT(50),
    SET_MAP_TAGGED_OBJECT_VISISBLE(51),
    SET_MAP_tAGGED_OBJECT_SMOOTH_VISIBLE(52),
    SET_MAP_TAGGED_OBJECT_ANIMATION(53),
    SET_MAP_OBJECT_ANIMATION(54),
    SET_MAP_OBJECT_VISIBLE(55),
    SET_MAP_OBJECT_MOVE(56),
    SET_MAP_OBJECT_CREATE_LAYER(57),
    SET_SPINE_BACK_EFFECT(58),
    SET_SPINE_OBJECT_EFFECT(59),
    CREATE_SPINE_RECT_EVENT(60),
    REMOVE_SPINE_RECT_EVENT(61),
    SPINE_RE_ADD_BACK_EVENT(62),
    SPINE_RE_ADD_OBJECT_EVENT(63),
    CREATE_CAMERA_CTRL_ZONE(64),
    REMOVE_CAMERA_CTRL_ZONE(65),
    UNK69(66),
    RELOAD_BACK(67),

    // CWvsContext::OnPacket
    INVENTORY_OPERATION(68),
    INVENTORY_GROW(69),
    STAT_CHANGED(70),
    TEMPORARY_STAT_SET(71),
    TEMPORARY_STAT_RESET(72),
    FORCED_STAT_SET(73),
    FORCED_STAT_RESET(74),
    CHANGE_SKILL_RECORD_RESULT(75),
    CHANGE_STEAL_MEMORY_RESULT(76),
    USER_DAMAGE_ON_FALLING_CHECK(77),
    PERSONAL_SHOP_BUY_CHECK(78),
    MOB_DROP_MESO_PICKUP(79),
    BREAK_TIME_FIELD_ENTER(80),
    RUNE_ACT_SUCCESS(81),
    RESULT_STEAL_SKILL_LIST(82),
    SKILL_USE_RESULT(83),
    EXCL_REQUEST(84),
    GIVE_POPULARITY_RESULT(85),
    MESSAGE(86),
    MEMO_RESULT(87),
    MAP_TRANSFER_RESULT(88),
    ANTI_MACRO_RESULT(89),
    ANTI_MACRO_BOMB_RESULT(90),
    //
    CLAIM_RESULT(92),
    SET_CLAIM_SVR_AVAILABLE_TIME(93),
    CLAIM_SVR_STATUS_CHANGED(94),
    STAR_PLANET_USER_COUNT(95),
    SET_TAMING_MOB_INFO(96),
    QUEST_CLEAR(97),
    ENTRUSTED_SHOP_CHECK_RESULT(98),
    SKILL_LEARN_ITEM_RESULT(99),
    SKILL_RESET_ITEM_RESULT(100),
    ABILITY_RESET_ITEM_RESULT(101),
    EXP_CONSUME_ITEM_RESULT(102),
    EXP_ITEM_GET_RESULT(103),
    CHAR_SLOT_INC_RESULT(104),
    CHAR_RENAME_RESULT(105),
    GATHER_ITEM_RESULT(106),
    SORT_ITEM_RESULT(107),
    //
    //
    CHARACTER_INFO(110),
    PARTY_RESULT(111),
    PARTY_MEMBER_CANDIDATE_RESULT(112),
    URUS_PARTY_MEMBER_CANDIDATE_RESULT(113),
    PARTY_CANDIDATE_RESULT(114),
    URUS_PARTY_RESULT(115),
    INTRUSION_FRIEND_CANDIDATE_RESULT(116),
    INTRUSION_LOBBY_CANDIDATE_RESULT(117),
    //
    EXPEDITION_RESULT(119),
    FRIEND_RESULT(120),
    STAR_FRIEND_RESULT(121),
    LOAD_ACCOUNT_ID_OF_CHARACTER_FRIEND_RESULT(122),
    GUILD_REQUEST(123),
    GUILD_RESULT(124),
    ALLIANCE_RESULT(125),
    TOWN_PORTAL(126),
    BROADCAST_MSG(127),
    //
    INCUBATOR_RESULT(129),
    INCUBATOR_HOT_ITEM_RESULT(130),
    SHOP_SCANNER_RESULT(131),
    SHOP_LINK_RESULT(132),
    AUCTION_RESULT(133),
    AUCTION_MESSAGE(134),
    MARRIAGE_REQUEST(135),
    MARRIAGE_RESULT(136),
    WEDDING_GIFT_RESULT(137),
    NOTIFY_MARRIED_PARTNER_MAP_TRANSFER(138),
    CASHPET_FOOD_RESULT(139),
    CASHPET_PICK_UP_ON_OFF_RESULT(140),
    CASHPET_SKILL_SETTING_RESULT(141),
    CASH_LOOK_CHANGE_RESULT(142),
    CASHPET_DYEING_RESULT(143),
    SET_WEEK_EVENT_MESSAGE(144),
    SET_POTION_DISCOUNT_RATE(145),
    BRIDLE_MOB_CATCH_FAIL(146),
    IMITATED_NPC_RESULT(147),
    IMITATED_NPC_DATA(148),
    //
    LIMITED_NPC_DISABLE_INFO(150),
    MONSTER_BOOK_SET_CARD(151),
    MONSTER_BOOK_SET_COVER(152),
    HOUR_CHANGE(153),
    MINIMAP_ON_OFF(154),
    CONSULT_AUTH_KEY_UPDATE(155),
    CLASS_COMPETITION_AUTH_KEY_UPDATE(156),
    WEB_BOARD_AUTH_KEY_UPDATE(157),
    SESSION_VALUE(158),
    PARTY_VALUE(159),
    FIELD_SET_VARIABLE(160),
    FIELD_VALUE(161),
    BONUS_EXP_RATE_CHANGED(162),
    FAMILY_CHART_RESULT(163),
    FAMILY_INFO_RESULT(164),
    FAMILY_RESULT(165),
    FAMILY_JOIN_REQUEST(166),
    FAMILY_JOIN_REQUEST_RESULT(167),
    FAMILY_JOIN_ACCEPTED(168),
    FAMILY_PRIVILEGE_LIST(169),
    FAMILY_FAMOUS_POINT_INC_RESULT(170),
    FAMILY_NOTIFY_LOGIN_OR_LOGOUT(171),
    FAMILY_SET_PRIVILEGE(172),
    FAMILY_SUMMON_REQUEST(173),
    NOTIFY_LEVEL_UP(174),
    NOTIFY_WEDDING(175),
    NOTIFY_JOB_CHANGE(176),
    SET_BUY_EQUIP_EXT(177),
    SET_PASSENSER_REQUEST(178), // typo?
    SCRIPT_PROGRESS_MESSAGE_BY_SOUL(179),
    SCRIPT_PROGRESS_MESSAGE(180),
    SCRUOT_PROGRESS_ITEM_MESSAGE(181),
    STATIC_SCREEN_MESSAGE(182),
    OFF_STATIC_SCREEN_MESSAGE(183),
    WEATHER_EFFECT_NOTICE(184),
    WEATHER_EFFECT_NOTICE_Y(185),
    PROGRESS_MESSAGE_FONT(186),
    DATA_CRC_CHECK_FAILED(187),
    SHOW_SLOT_MESSAGE(188),
    WILD_HUNTER_INFO(189),
    ZERO_INFO(190),
    ZERO_WP(191),
    ZERO_INFO_SUB_HP(192),
    UI_OPEN(193),
    CLEAR_ANNOUNCED_QUEST(194),
    RESULT_INSTANCE_TABLE(195),
    COOL_TIME_SET(196),
    ITEM_POT_CHANGE(197),
    SET_ITEM_COOL_TIME(198),
    SET_AD_DISPLAY_INFO(199),
    SET_AD_DISPLAY_STATUS(200),
    SET_SON_OF_LINKED_SKILL_RESULT(201),
    SET_MAPLE_STYLE_INFO(202),
    SET_BUY_LIMIT_COUNT(203),
    RESET_BUY_LIMIT_COUNT(204),
    UPDATE_UI_EVENT_LIST_INFO(205),
    DOJANG_RANKING_RESULT(206),
    //
    //
    SHUTDOWN_MESSAGE(209),
    RESULT_SET_STEAL_SKILL(210),
    SLASH_COMMAND(211),
    START_NAVIGATION(212),
    FUNCKEY_SET_BY_SCRIPT(213),
    CHARACTER_POTENTIAL_SET(214),
    CHARACTER_POTENTIAL_RESET(215),
    CHARACTER_HONOR_EXP(216),
    CHARACTER_HONOR_EXP_JP(217), // 日版十字獵人遠征點數 int int
    ASWAN_STATE_OnPacket(218), // if ( TSingleton<CUIAswanState>::ms_pInstance ) CUIAswanState::OnPacket(iPacket);
    ASWAN_RESULT(219),
    READY_FOR_RESPAWN(220),
    READY_FOR_RESPAWN_BY_POINT(221),
    OPEN_READY_FOR_RESPAWN_UI(222),
    CHARACTER_HONOR_GIFT(223),
    CROSS_HUNTER_COMPLETE_RESULT(224),
    CROSS_HUNTER_SHOP_RESULT(225),
    SET_CASH_ITEM_NOTICE(226),
    SET_SPECIAL_CASH_ITEM(227),
    SHOW_EVENT_NOTICE(228),
    BOARD_GAME_RESULT(229),
    YUT_GAME_RESULT(230),
    VALUE_PACK_RESULT(231),
    NAVI_FLYING_RESULT(232),
    SET_EXCL_REQUEST_SENT(233),
    CHECK_WEDDING_EX_RESULT(234),
    BINGO_RESULT(235),
    BINGO_CASSANDRA_RESULT(236),
    UPDATE_VIP_GRADE(237),
    MESO_RANGER_RESULT(238),
    SET_MAPLE_POINT(239),
    //
    SET_MIRACLE_TIME_INFO(241),
    HYPER_SKILL_RESET_RESULT(242),
    GET_SERVER_TIME(243),
    GET_CHARACTER_POSITION(244),
    //
    RETURN_EFFECT_CONFIRM(246),
    RETURN_EFFECT_MODIFIED(247),
    WHITE_ADDTIONAL_CUBE_RESULT(248),
    BLACK_CUBE_RESULT(249),
    MEMORIAL_CUBE_RESULT(250),
    MEMORIAL_CUBE_MODIFIED(251),
    DRESS_UP_INFO_MODIFIED(252),
    RESET_STATE_FOR_OFF_SKILL(253),
    SET_OFF_STATE_FOR_OFF_SKILL(254),
    ISSUE_RELOGIN_COOKIE(255),
    AVATAR_PACK_TEST(256),
    EVOLVING_RESULT(257),
    ACTION_BAR_RESULT(258),
    //
    GUILD_SEARCH_RESULT(260),
    //
    HALLOWEEN_CANDY_RANKING_RESULT(262),
    GET_REWARD_RESULT(263),
    MENTORING(264),
    GET_LOTTERY_RESULT(265),
    CHECK_PROCESS_RESULT(266),
    COMPLETE_NPC_SPEECH_SUCCESS(267),
    COMPLETE_SPECIAL_CHECK_SUCCESS(268),
    SET_ACCOUNT_INFO(269),
    SET_GACHAPFEVER_TIME_INFO(270),
    AVATAR_MEGAPHONE_RES(271),
    SET_AVATAR_MEGAPHONE(272),
    CLEAR_AVATAR_MEGAPHONE(273),
    REQUEST_EVENT_LIST(274),
    LIKE_POINT(275),
    SIGN_ERROR_ACK(276),
    ASK_AFTER_ERROR_ACK(277),
    EVENT_NAME_TAG(278),
    ACQUIRE_EVENT_NAME_TAG(279),
    JOB_FREE_CHANGE_RESULT(280),
    EVENT_LOTTERY_OPEN(281),
    EVENT_LOTTERY_RESULT(282),
    //
    //
    //
    //
    //
    //
    //
    SCREEN_MSG(290),
    LIMIT_GOODS_NOTICE_RESULT(291),
    //
    MONSTER_BATTLE_SYSTEM_RESULT(293),
    MONSTER_BATTLE_COMBAT_RESULT(294),
    //
    UNIVERSE_BOSS_IMPOSSIBLE(296),
    CASH_SHOP_PREVIEW_INFO(297),
    CHANGE_SOUL_COLLECTION_RESULT(298),
    SELECT_SOUL_COLLECTION_RESULT(299),
    MASTER_PIECE_REWARD(300),
    PENDANT_SLOT_INC_RESULT(301),
    BOSS_ARENA_MATCH_SUCCESS(302),
    BOSS_ARENA_MATCH_FAIL(303),
    BOSS_ARENA_MATCH_REQUEST_DONE(304),
    USER_SOUL_MATCHING(305),
    CATAPULT_UPGRADE_SKILL(306),
    CATAPULT_RESET_SKILL(307),
    PARTY_QUEST_RANKING_RESULT(308),
    SET_COORDINATION_CONTEST_INFO(309),
    WORLD_TRANSFER_RESULT(310),
    TRUNK_SLOT_INC_RESULT(311),
    ELITE_MOB_WMI(312),
    RANDOM_PORTAL_NOTICE(313),
    NOTIFY_WORLD_TRANSFER_HELPER(314),
    EQUIPMENT_ENCHANT(315),
    TOP_TOWER_RANK_RESULT(316),
    FRIEND_TOWER_RANK_RESULT(317),
    TOWER_RESULT_UI_OPEN(318),
    MANNEQUIN_RESULT(319),
    IRON_BOX_PACKET(320),
    CREATE_KOREAN_JUMPING_GAME(321),
    CREATE_SWING_GAME(322),
    CREATE_VIOLETA_HOPE_GAME(323),
    UPDATE_MAPLE_TV_SHOW_TIME(324),
    RETURN_TO_TITLE(325),
    RETURN_TO_CHARACTER_SELECT(326),
    FLAME_WIZARD_FLAME_WALK_EFFECT(327),
    FLAME_WIZARD_FLARE_BLINK(328),
    SUMMONED_AVATAR_SYNC(329),
    // 這裡ㄧ堆韓版沒有的
    CASH_SHOP_EVENT_INFO(375),
    BLACK_LIST(376),
    OPEN_UI_TEST(377),
    SWITCH_BLACK_LIST_VIEW(378),
    SCROLL_UPGRADE_FEVER_TIME(379),
    TEXT_EQUIP_INFO(380),
    TEXT_EQUIP_UI_OPEN(381),
    UI_STAR_PLANET_MINI_GAME_RESULT(382),
    UI_STAR_PLANET_TREND_SHOP(383),
    UI_STAR_PLANET_MINI_GAME_QUEUE(384),
    //
    STAR_PLANET_ROUND_INFO(386),
    STAR_PLANET_RESULT(387),
    BACK_SPEED_CTRL(388),
    SET_MAZE_AREA(389),
    CHARACTER_BURNING(390),
    BATTLE_STAT_CORE_INFO(391),
    BATTLE_STAT_CORE_ACK(392),
    GACHAPON_TEST_RESULT(393),
    MASTER_PIECE_TEST_RESULT(394),
    ROYAL_STYLE_TEST_RESULT(395),
    BEAUTY_COUPTEST_RESULT(396),
    NICK_SKILL_EXPIRED(397),
    RANDOM_MISSION_RESULT(398),
    ON_12TH_TRESURE_RESULT(399),
    ON_12TH_TRESURE_BUFF(400),
    ITEM_COLLECTION_RESULT(401),
    CHECK_COLLECTION_COMPLETE_RESULT(402),
    ITEM_COLLECTION_LIST(403),
    RECEIVE_TOADS_HAMMER_REQUEST_RESULT(404),
    RECEIVE_HYPER_STAT_SKILL_RESET_RESULT(405),
    INVENTORY_OPERATION_RESULT(406),
    GET_SAVED_URUS_SKILL(407),
    SET_ROLE_PLAYING_CHARACTER_INFO(408),
    MVP_ALARM(409),
    MONSTER_COLLECTION_RESULT(410),
    TOWER_CHAIR_SETTING_RESULT(411),
    NEED_CLIENT_RESPONSE(412),
    CHARACTER_MODIFIED(413),
    TRADE_KING_SHOP_ITEM(414),
    TRADE_KING_SHOP_RES(415),
    PLATFORMAR_ENTER_RESULT(416),
    PLATFORMAR_OXYZEN(417),
    //
    GUILD_BBS_RESULT(-1),
    //
    MACRO_SYS_DATA_INIT(427),

    // CStage::OnPacket : v176 -> 00E75B70
    SET_FIELD(428),
    SET_FARM_FIELD(429),
    SET_MTS(430),
    SET_CASH_SHOP(431),
    SET_CASH_SHOP_INFO(432),

    // CField::OnPacket (general) : v176 -> 00844E10
    TRANSFER_FIELD_REQ_IGNORED(433),
    TRANSFER_CHANNEL_REQ_IGNORED(434),
    TRANSFER_PVP_REQ_IGNORED(435),
    FIELD_SPECIFIC_DATA(436),
    GROUP_MESSAGE(437),
    FIELD_UNIVERSE_MESSAGE(438),
    WHISPER(439),
    SUMMITEM_INAVAILABLE(440),
    FIELD_EFFECT(441),
    BLOW_WEATHER(442),
    //
    PLAY_JUKE_BOX(444),
    ADMIN_RESULT(445),
    QUIZ(446),
    FIELD_SET_DESC(447),
    CLOCK(448),
    //
    //
    SET_QUEST_CLEAR(451),
    SET_QUEST_TIME(452),
    SET_OBJECT_STATE(453),
    DESTROY(454),
    //
    STALK_RESULT(456),
    // CField_Massacre::OnPacket
    MASSACRE_INC_GAUGE(457),
    MASSACRE_RESULT(458),
    // CField::OnPacket
    INIT(459),
    FOOT_HOLD_MOVE(460),
    CORRECT_FOOT_HOLD_MOVE(461),
    //
    //
    FOOT_HOLD_APPEAR(464),
    FIELD_KILL_COUNT(465), // CField_KillCount::OnPacket
    SMART_MOB_NOTICE(466),
    CHANGE_PHASE(467),
    CHANGE_MOB_ZONE(468),
    //
    PVP_MIGRATE_INFO_RESULT(470),
    CUR_NODE_EVENT_END(471),
    CREATE_FORCE_ATOM(472),
    SET_ACHIEVE_RATE(473),
    SET_QUICK_MOVE_INFO(474),
    CHANGE_ASWAN_SIEGE_WEAPGAUGE(475),
    CREATE_OBTACLE(476),
    CLEAR_OBTACLE(477),
    //
    B2_FOOT_HOLD_CREATE(479),
    DEBUFF_OBJ_ON(480),
    //
    //
    CREATE_FALLING_CATCHER(483),
    CHASE_EFFECT_SET(484),
    MESO_EXCHANGE_RESULT(-1),
    SET_MIRROR_DUNGEINFO(485),
    SET_INTRUSION(486),
    CANNOT_DROP(487),
    FOOT_HOLD_OFF(488),
    LADDER_ROPE_OFF(489),
    MOMENT_AREA_OFF(490),
    MOMENT_AREA_OFF_ALL(491),
    CHAT_LET_CLIENT_CONNECT(492),
    CHAT_INDUCE_CLIENT_CONNECT(493),
    UI_CoordinationContest(494),
    ELITE_STATE(495),
    PLAY_SOUND(496),
    STACK_EVENT_GAUGE(497),
    //
    //
    //
    //
    SET_UNION_FIELD(502),
    //
    STAR_PLANET_BURNING_TIME_INFO(504),
    PUBLIC_SHARE_STATE(505),
    FUNCTION_TEMP_BLOCK(506),
    UI_STATUS_BAR_PACKET(507),
    FIELD_SKILL_DELAY(508),
    WEATHER_PACKET_ADD(509),
    WEATHER_PACKET_REMOVE(510),
    WEATHER_PACKET_MSG(511),
    ADD_WRECKAGE(512),
    DEL_WRECKAGE(513),
    CREATE_MIRROR_IMAGE(514),
    FUNTION_FOOTHOLD_MAN(515),
    //

    // CUserPool::OnPacket?
    USER_ENTER_FIELD(517),
    USER_LEAVE_FIELD(USER_ENTER_FIELD, 1),

    // CUserPool::OnCommonPacket : v176 -> 018566C0
    CHAT(519),
    //
    AD_BOARD(521),
    MINI_ROOM_BALLOON(522),

    SET_CONSUME_ITEM_EFFECT(521),
    SHOW_ITEM_UPGRADE_EFFECT(522),
    SHOW_ITEM_SKILL_SOCKET_UPGRADE_EFFECT(524),
    SHOW_ITEM_SKILL_OPTION_UPGRADE_EFFECT(525),
    SHOW_ITEM_RELEASE_EFFECT(526),
    SHOW_ITEM_UNRELEASE_EFFECT(527),
    SHOW_ITEM_LUCKY_ITEM_EFFECT(528),
    SHOW_ITEM_MEMORIAL_EFFECT(529),
    SHOW_ITEM_ADDITIONAL_UN_RELEASE_EFFECT(530),
    SHOW_ITEM_ADDITIONAL_SLOT_EXTEND_EFFECT(531),
    SHOW_ITEM_FIRE_WORKS_EFFEC(532),
    SHOW_ITEM_OPTION_CHANGE_EFFECT(533),
    RED_CUBE_RESULT(534),
    HIT_BY_USER(535), // OnHitByUser -> KMST, verified v176 idb
    DOT_BY_USER(536), // OnDotByUser
    RESET_ALL_DOT(537), // OnResetAllDot
    DAMAGE_BY_USER(538), // OnDamageByUser
    TESLA_TRIANGLE(539),
    FOLLOW_CHARACTER(540),
    SHOW_PQ_REWARD(541),
    SET_ONE_TIME_ACTION(542),
    MAKING_SKILL_RESULT(543),
    SET_MAKING_MEISTER_SKILL_EFF(544),
    GATHER_RESULT(545),
    USER_EXPLODE(546),
    USER_HIT_BY_COUNTER(547),
    PYRAMID_LETHAL_ATTACK(548),
    MIXER_RESULT(549),
    WAIT_QUEUE_RESPONSE(550),
    CATEGORY_EVENT_NAME_TAG(551),
    SET_DAMAGE_SKIN(552),
    SET_PREMIUM_DAMAGE_SKIN(553),
    SET_SOUL_EFFECT(554),
    SIT_RESULT(555),
    STAR_PLANET_POINT_INFO(556),
    STAR_PLANET_AVATAR_LOOK_SET(557),
    TOSSED_BY_MOB_SKILL(575),
    BATTLE_ATTACK_HIT(),
    BATTLE_USER_HIT_BY_MOB(),
    FREEZE_HOT_EVENT_INFO(),
    EVENT_BEST_FRIEND_INFO(),
    SET_REPEAT_ONE_TIME_ACTION(),
    SET_REPLACE_MOVE_ACTION(),
    IN_GAME_CUBE_RESULT(),
    SET_ACTIVE_EMOTICON_ITEM(),
    CREATE_PSYCHIC_LOCK(),
    RECREATE_PATHPSYCHIC_LOCK(),
    RELEASE_PSYCHIC_LOCK(),
    RELEASE_PSYCHIC_LOCK_MOB(),
    CREATE_PSYCHIC_AREA(),
    RELEASE_PSYCHIC_AREA(),
    RW_ZERO_BUNKER_MOB_BIND(),
    BEAST_FORM_WING_OFF(),
    SET_MESO_CHAIR_COUNT(),
    REFRESH_NAME_TAG_MARK(),
    STIGMA_EFFECT(595),
//    SHOW_POTENTIAL_BLACK_CUBE(529),
    GACHAPON_EFFECT(0),

    // CUser::OnPetPacket
    PET_ACTIVATED(596),
    PET_MOVE(597),
    PET_ACTION(598),
    PET_ACTION_SPEAK(599),
    PET_NAME_CHANGED(600),
    PET_LOAD_EXCEPTION_LIST(601),
    PET_HUE_CHANGED(602),
    PET_MODIFIED(603),
    //
    //
    PET_ACTION_COMMAND(606),

    // CUser::OnDragonPacket
    DRAGON_CREATED(607),
    DRAGON_MOVE(608),
    DRAGON_REMOVE(609),
    DRAGON_REMOVE_RP_CHAR(610),

    // CUser::OnAndroidPacket
    ANDROID_CREATED(611),
    ANDROID_MOVE(612),
    ANDROID_ACTION_SET(613),
    ANDROID_MODIFIED(614),
    ANDROID_REMOVED(615),

    // CUser::OnFoxManPacket
    FOX_MAN_ENTER_FIELD(616),
    FOX_MAN_MOVE(617),
    FOX_MAN_EXCL_RESULT(618),
    FOX_MAN_SHOW_CHANGE_EFFECT(619),
    FOX_MAN_MODIFIED(620),
    FOX_MAN_LEAVE_FIELD(621),
    //

    // CUser::OnSkillPetPacket
    SKILL_PET_MOVE(623),
    SKILL_PET_ACTION(624),
    SKILL_PET_STATE(625),

    // CFamiliar::OnPacket
    FAMILIAR_ENTER_FIELD(626),
    FAMILIAR_MOVE(627),
    FAMILIAR_HIT(628),
    FAMILIAR_ATTACK(629),
    FAMILIAR_RENAME(630),
    FAMILIAR_TRANSFER_FIELD(631),
    FAMILIAR_UPDATE_INFO(632),
    //

    // CUserRemote::OnPacket : v176 -> 018548E0
    REMOTE_MOVE(634),
    REMOTE_MELEE_ATTACK(635),
    REMOTE_SHOOT_ATTACK(636),
    REMOTE_MAGIC_ATTACK(637),
    REMOTE_BODY(638),
    REMOTE_SKILL_PREPARE(639),
    REMOTE_MOVING_SHOOT_ATTACK_PREPARE(640),
    REMOTE_SKILL_CANCEL(640),
    REMOTE_HIT(641),
    REMOTE_EMOTION(642),
    REMOTE_ANDROID_EMOTION(643),
    REMOTE_SET_ACTIVE_EFFECT_ITEM(644),
    REMOTE_SET_MONKEY_EFFECT_ITEM(645),
    REMOTE_SET_ACTIVE_NICK_ITEM(646),
    REMOTE_SET_DEFAULT_WING_ITEM(647),
    REMOTE_SET_KAISER_TRANSFORM_ITEM(648),
    REMOTE_SET_CUSTOM_RIDING(649),
    REMOTE_SHOW_UPGRADE_TOMB_EFFECT(650),
    REMOTE_SET_ACTIVE_PORTABLE_CHAIR(651),
    REMOTE_AVATAR_MODIFIED(652),
    REMOTE_SET_TEMPORARY_STAT(654),
    REMOTE_RESET_TEMPORARY_STAT(655),
    REMOTE_RECEIVE_HP(656),
    REMOTE_GUILD_NAME_CHANGED(657),
    REMOTE_GUILD_MARK_CHANGED(658),
    REMOTE_PVP_TEAM_CHANGED(659),
    REMOTE_UPDATE_PVP_HP_TAG(661),
    REMOTE_DRAGON_GLIDE(662),
    REMOTE_KEY_DOWN_AREA_MOVE_PATH(663),
    REMOTE_LASER_INFO_FOR_REMOTE(664),
    REMOTE_KAISER_COLOR_OR_MORPH_CHANGE(665),
    REMOTE_INTRUSION(669),
    REMOTE_ZERO_LAST_ASSIST_STATE(670),
    REMOTE_SCOUTER_MAX_DAMAGE_UPDATE(679),
    REMOTE_STIGMA_DELIVERY_RESPONSE(680),
    REMOTE_EFFECT(653),
    REMOTE_GATHER_ACTION_SET(660),
    REMOTE_DESTROY_GRENADE(666),
    REMOTE_SET_ITEM_ACTION(667),
    REMOTE_ZERO_TAG(668),
    REMOTE_SET_MOVE_GRENADE(671),
    REMOTE_SET_CUSTOMIZE_EFFECT(672),
    REMOTE_RUNE_STONE_ACTION(673),
    REMOTE_KINESIS_PSYCHIC_ENERGY_SHIELD_EFFECT(674),
    REMOTE_DRAGON_ACTION(675),
    REMOTE_DRAGON_BREATH_EARTH_EFFECT(676),
    REMOTE_RELEASE_RW_GRAB(677),
    REMOTE_RW_MULTI_CHARGE_CANCEL_REQUEST(678),
    REMOTE_THROW_GRENADE(684),

    // CUserLocal::OnPacket
    EMOTION(688),
    ANDROID_EMOTION(689),
    EFFECT(690),
    TELEPORT(691),
    //
    MESO_GIVE_SUCCEEDED(693),
    MESO_GIVE_FAILED(694),
    QUEST_RESULT(695),
    NOTIFY_HP_DEC_BY_FIELD(696),
    USER_PET_SKILL_CHANGED(697),
    BALLOON_MSG(698),
    PLAY_EVENT_SOUND(699),
    PLAY_MINIGAME_SOUND(700),
    MAKER_RESULT(701),
    //
    OPEN_CLASS_COMPETION_TIPAGE(703),
    OPEN_UI(704),
    CLOSE_UI(705),
    OPEN_UI_WITH_OPTION(706),
    OPEN_WEB_UI(707),
    SET_DIRECTION_MODE(708),
    SET_IN_GAME_DIRECTION_MODE(709),
    SET_STAND_ALONE_MODE(710),
    HIRE_TUTOR(711),
    TUTOR_MSG(712),
    HIRE_TUTOR_BY_ID(713),
    SET_PARTNER(714),
    SET_PARTNER_ACTION(715),
    SET_PARTNER_FORCE_FLIP(716),
    SWITCH_RP(717),
    MOD_COMBO_RESPONSE(718),
    INC_COMBO_RESPONSE_BY_COMBO_RECHARGE(719),
    RADIO_SCHEDULE(720),
    OPEN_SKILL_GUIDE(721),
    NOTICE_MSG(722),
    CHAT_MSG(723),
    SET_UTIL_DLG(724),
    BUFFZONE_EFFECT(725),
    TIME_BOMB_ATTACK(726),
    EXPLOSION_ATTACK(727),
    PASSIVE_MOVE(728),
    FOLLOW_CHARACTER_FAILED(729),
    SET_NEXT_SHOOT_EX_JABLIN(730),
    RESULT(731),
    GATHER_REQUEST_RESULT(732),
    RUNE_STONE_USE_ACK(733),
    BAG_ITEM_USE_RESULT(734),
    RANDOM_TELEPORT_KEY(735),
    SET_GAGE_POINT(736),
    IN_GAME_DIRECTION_EVENT(737),
    MEDAL_REISSUE_RESULT(738),
    DODGE_SKILL_READY(739),
    REMOVE_MICRO_BUFF_SKILL(740),
    VIDEO_BY_SCRIPT(741),
    REWARD_MOB_LIST_RESULT(742),
    INC_JUDGEMENT_STACK_RESPONSE(743),
    INC_CHARM_BY_CASHP_R_MSG(744),
    SET_BUFF_PROTECTOR(745),
    INC_LARKNESS_RESPONSE(746),
    DETONATE_BOMB(747),
    AGGRO_RANK_INFO_NAME(748),
    DEATH_COUNT_INFO(749),
    DEATH_COUNT_INFO_2(750),
    SET_DRESS_CHANGED(751),
    SERVER_ACK_MOB_ZONE_STATE_CHANGE(752),
    //null?
    //null?
    RANDOM_EMOTION(755),
    SET_FLIP_THE_COIN_ENABLED(756),
    TRICK_OR_TREAT_RESULT(757),
    GIANT_PET_BUFF(758),
    B2_BODY_RESULT(759),
    SET_DEAD(760),
    OPEN_UI_DEAD(761),
    EXPIRED_NOTICE(762),
    DO_LOTTERY_UI(763),
    ROULETTE_START(764),
    SIT_TIME_CAPSULE(765),
    SIT_DUMMY_PORTABLE_CHAIR(766),
    GO_MONSTER_FARM(767),
    MONSTER_LIFE_INVITE_ITEM_RESULT(768),
    PHOTO_GET_RESULT(769),
    FINAL_ATTACK_REQUEST(770),
    SET_GUN(771),
    SET_AMMO(SET_GUN, 1),
    CREATE_GUN(SET_GUN, 2),
    CLEAR_GUN(SET_GUN, 3),
    RESULT_SHOOT_ATTACK_IN_FPS_MODE(SET_GUN, 4),
    MIRROR_DUNGEENTER_FAIL(SET_GUN, 5),
    MIRROR_DUNGEUNIT_CLEARED(SET_GUN, 6),
    REGISTER_MIRROR_DUNGEBOSS(SET_GUN, 7),
    MIRROR_DUNGERECORD(SET_GUN, 8),
    OPEN_URL(SET_GUN, 9),
    ZERO_COMBAT_RECOVERY(SET_GUN, 10),
    MIRROR_STUDY_UI_OPEN(782),
    SKILL_COOLTIME_REDUCE(MIRROR_STUDY_UI_OPEN, 1),
    MIRROR_READING_UI_OPEN(MIRROR_STUDY_UI_OPEN, 2),
    USER_CTRL_MOB_SKILL_Q_PUSH(MIRROR_STUDY_UI_OPEN, 3),
    ZERO_LEVEL_UP_ALARM(MIRROR_STUDY_UI_OPEN, 4),
    USER_CTRL_MOB_SKILL_Q_POP(MIRROR_STUDY_UI_OPEN, 5),
    USER_CTRL_MOB_SKILL_FAIL(MIRROR_STUDY_UI_OPEN, 6),
    FORCE_SUMMONED_REMOVE(MIRROR_STUDY_UI_OPEN, 7),
    USER_RESPAWN(MIRROR_STUDY_UI_OPEN, 8),
    USER_CTRL_MOB_SKILL_FORCED_POP(MIRROR_STUDY_UI_OPEN, 9),
    MONSTER_BATTLE_CAPTURE(MIRROR_STUDY_UI_OPEN, 10),
    IS_UNIVERSE(793),
    PORTAL_GROUP(IS_UNIVERSE, 1),
    SET_MOVABLE(IS_UNIVERSE, 2),
    USER_CTRL_MOB_SKILL_PUSH_COOL_TIME(IS_UNIVERSE, 3),
    MOVE_PARTICLE_EFF(IS_UNIVERSE, 4),
    DO_ACTIVE_EVENT_SKILL_BY_SCRIPT(IS_UNIVERSE, 5),
    SET_STATUSBAR_JOB_NAME_BLUR(IS_UNIVERSE, 6),
    RUNE_STONE_SKILL_ACK(800),
    RESET_RUNE_STONE_ACTION(RUNE_STONE_SKILL_ACK, 1),
    MOVE_TO_CONTENTS_CANNOT_MIGRATE(RUNE_STONE_SKILL_ACK, 2),
    PLAY_AMBIENT_SOUND(RUNE_STONE_SKILL_ACK, 3),
    STOP_AMBIENT_SOUND(RUNE_STONE_SKILL_ACK, 4),
    FLAME_WIZARD_ELEMENT_FLAME_SUMMON(RUNE_STONE_SKILL_ACK, 5),
    CAMERA_MODE(RUNE_STONE_SKILL_ACK, 6),
    SPOTLIGHT_TO_CHARACTER(RUNE_STONE_SKILL_ACK, 7),
    BOSS_PARTY_CHECK_DONE(RUNE_STONE_SKILL_ACK, 8),
    FREE_LOOK_CHANGE_UI_OPEN(RUNE_STONE_SKILL_ACK, 9),
    FREE_LOOK_CHANGE_SUCCESS(RUNE_STONE_SKILL_ACK, 10),
    GRAY_BACKGROUND(811),

    // 812 ~ 857 海外專屬包頭
    MOVE_SCRREN_DOWN(822),

    GET_NPC_CURRENT_ACTION(858),
    CAMERA_ROTATION(GET_NPC_CURRENT_ACTION, 1),
    CAMERA_SWITCH(GET_NPC_CURRENT_ACTION, 2),
    NETWORK(GET_NPC_CURRENT_ACTION, 3),
    USER_SET_FIELD_FLOATING(GET_NPC_CURRENT_ACTION, 4),
    ADD_POPUP_SAY(GET_NPC_CURRENT_ACTION, 5),
    REMOVE_POPUP_SAY(GET_NPC_CURRENT_ACTION, 6),
    JAGUAR_SKILL(865),
    ACTION_LAYER_RELMOVE(JAGUAR_SKILL, 1),
    SEND_CLIENT_RESOLUTION(JAGUAR_SKILL, 2),
    USER_BONUS_ATTACK_REQUEST(JAGUAR_SKILL, 3),
    USER_RAND_AREA_ATTACK_REQUEST(JAGUAR_SKILL, 4),
    JAGUAR_ACTIVE(JAGUAR_SKILL, 5),
    SKILL_COOLTIME_SET_M(JAGUAR_SKILL, 6),
    SET_CARRY_REACTOR_INFO(JAGUAR_SKILL, 7),
    REACTOR_SKILL_USE_REQUEST(JAGUAR_SKILL, 8),
    OPEN_BATTLE_PVP_PCHAMP_SELECT_UI(JAGUAR_SKILL, 9),
    BATTLE_PVP_ITEM_DROP_SOUND(JAGUAR_SKILL, 10),
    SET_MESO_COUNT_BY_SCRIPT(JAGUAR_SKILL, 11),
    PLANT_POT_CLICK_RESULT(JAGUAR_SKILL, 12),
    PLANT_POT_EFFECT(JAGUAR_SKILL, 13),
    DAMAGE(879),
    ROYAL_GUARD_ATTACK(DAMAGE, 1),
    DO_ACTIVE_PSYCHIC_AREA(DAMAGE, 2),
    ENTER_FIELD_PSYCHIC_INFO(DAMAGE, 3),
    LEAVE_FIELD_PSYCHIC_INFO(DAMAGE, 4),
    TOUCH_ME_STATE_RESULT(DAMAGE, 5),
    FIELD_SCORE_UPDATE(DAMAGE, 6),
    URUS_REUSLT_UI_OPEN(DAMAGE, 7),
    SET_NO_MORE_LIFE(DAMAGE, 8),
    SOME_DECODE4(DAMAGE, 9),
    CREATE_AREA_DOT_INFO(DAMAGE, 10),
    SET_SLOW_DOWN(DAMAGE, 11),
    REGISTER_EXTRA_SKILL(DAMAGE, 12),
    RES_WARRIOR_LIFT_MOB_INFO(DAMAGE, 13),
    USER_RENAME_RESULT(DAMAGE, 14),
    DAMAGE_SKIN_SAVE_RESULT(DAMAGE, 15),
    STIGMA_REMAIN_TIME(895),
    OPEN_MESO_SACK_SUCCESS(),
    OPEN_MESO_SACK_FAIL(),

    FAMILIAR_ADD_RESULT(),
    FAMILIAR_INVALID_NAME(),

    MOD_HAYATO_COMBO(),
    //
    //
    //
    SKILL_COOLTIME_SET(897),
    //

    // CSummonedPool::OnPacket
    SUMMONED_CREATED(899),
    SUMMONED_REMOVED(SUMMONED_CREATED, 1),
    SUMMONED_MOVE(SUMMONED_CREATED, 2),
    SUMMONED_ATTACK(SUMMONED_CREATED, 3),
    SUMMONED_ATTACK_PVP(SUMMONED_CREATED, 4),
    SUMMONED_SET_REFERENCE(SUMMONED_CREATED, 5),
    SUMMONED_SKILL(SUMMONED_CREATED, 6),
    SUMMONED_SKILL_PVP(SUMMONED_CREATED, 7),
    SUMMONED_UPDATE_HP_TAG(SUMMONED_CREATED, 8),
    SUMMONED_ATTACK_DONE(SUMMONED_CREATED, 9),
    SUMMONED_SET_RESIST(SUMMONED_CREATED, 10),
    SUMMONED_ACTION_CHANGE(SUMMONED_CREATED, 11),
    SUMMONED_ASSIST_ATTACK_REQUEST(SUMMONED_CREATED, 12),
    SUMMONED_SUMMON_ATTACK_ACTIVE(SUMMONED_CREATED, 13),
    SUMMONED_BEHOLDER_REVENGE_ATTACK(SUMMONED_CREATED, 14),
    SUMMONED_HIT(SUMMONED_CREATED, 15),

    // CMobPool::OnPacket
    MOB_ENTER_FIELD(915),
    MOB_LEAVE_FIELD(),
    MOB_CHANGE_CONTROLLER(),
    MOB_SET_AFTER_ATTACK(),
    MOB_BLOCK_ATTACK(),
    MOB_CRC_KEY_CHANGED(931),

    // CMobPool::OnMobPacket
    MOB_MOVE(921),
    MOB_CONTROL_ACK(MOB_MOVE, 1),
    //null
    MOB_STAT_SET(MOB_MOVE, 3),
    MOB_STAT_RESET(MOB_MOVE, 4),
    MOB_SUSPEND_RESET(MOB_MOVE, 5),
    MOB_AFFECTED(MOB_MOVE, 6),
    MOB_DAMAGED(MOB_MOVE, 7),
    MOB_SPECIAL_EFFECT_BY_SKILL(MOB_MOVE, 8),
    //null
    //null
    MOB_CRC_DATA_REQUEST(MOB_MOVE, 11),
    MOB_HP_INDICATOR(MOB_MOVE, 12),
    MOB_CATCH_EFFECT(MOB_MOVE, 13),
    MOB_STEAL_EFFECT(MOB_MOVE, 14),
    MOB_EFFECT_BY_ITEM(MOB_MOVE, 15),
    MOB_SPEAKING(MOB_MOVE, 16),
    MOB_MESSAGING(MOB_MOVE, 17),
    MOB_SKILL_DELAY(MOB_MOVE, 18),
    ESCORT_FULL_PATH(MOB_MOVE, 19),
    ESCORT_STOP_END_PERMISSION(MOB_MOVE, 20),
    ESCORT_STOP_BY_SCRIPT(MOB_MOVE, 21),
    ESCORT_STOP_SAY(MOB_MOVE, 22),
    ESCORT_RETURN_BEFORE(MOB_MOVE, 23),
    MOB_NEXT_ATTACK(MOB_MOVE, 24),
    MOB_TELEPORT_REQUEST(MOB_MOVE, 25),
    MOB_FORCED_ACTION(MOB_MOVE, 26),
    MOB_FORCED_SKILL_ACTION(MOB_MOVE, 27),
    //
    MOB_TIME_RESIST(MOB_MOVE, 29),
    MOB_ONEKILL_DAMAGE(MOB_MOVE, 30),
    MOB_ATTACK_BLOCK(MOB_MOVE, 31),
    MOB_ATTACK_PRIORITY(MOB_MOVE, 32),
    MOB_ATTACK_TIME_INFO(MOB_MOVE, 33),
    MOB_DAMAGE_SHARE_INFO_TO_LOCAL(MOB_MOVE, 34),
    MOB_DAMAGE_SHARE_INFO_TO_REMOTE(MOB_MOVE, 35),
    MOB_BREAK_DOWN_TIME_ZONE_TIME_OUT(MOB_MOVE, 36),
    MOB_MOVE_AREA_SET(MOB_MOVE, 37),
    MOB_DO_SKILL_BY_HIT(MOB_MOVE, 38),
    MOB_CASTING_BAR_SKILL(MOB_MOVE, 40),
    MOB_FLY_TARGET(MOB_MOVE, 41),
    MOB_BOUNCE_ATTACK_SKILL(MOB_MOVE, 42),
    MOB_AREA_INSTALL_BY_HIT(956),
    MOB_LTRB_DAMAGE_SKILL(957),
    MOB_SUMMSUB_BODY(958),
    MOB_LASER_CONTROL(959),
    MOB_SCALE(960),
    //
    //
    MOB_FORCE_CHASE(963),
    MOB_HANG_OVER_REQUEST(964),
    MOB_HANG_OVER_RELEASE_REQUEST(965),
    MOB_DEAD_FPS_MODE(966),
    MOB_AIR_HIT(967),
    MOB_DEMIAN_DELAYED_ATTACK_CREATE(968),
    MOB_REGISTER_REL_MOB_ZONE(969),
    MOB_UNREGISTER_REL_MOB_ZONE(970),
    MOB_NEXT_TARGET_FROM_SVR(971),
    //
    //
    //
    //
    //
    //
    MOB_ATTACKED_BY_MOB(978),

    // CMinionPool::OnPacket
    MINION_ENTER_FIELD(989),
    MINION_LEAVE_FIELD(MINION_ENTER_FIELD, 1),
    MINION_CHANGE_CONTROLLER(MINION_ENTER_FIELD, 2),
    MINION_GEN_BEYOND_SPLIT(MINION_ENTER_FIELD, 3),

    // CNpcPool::OnPacket : v176 -> 00CB5250
    NPC_IMITATE_DATA(148),
    NPC_UPDATE_LIMITED_DISABLE_INFO(NPC_IMITATE_DATA, 2),
    SET_NPC_SCRIPT(1015),
    NPC_ENTER_FIELD(993),
    NPC_LEAVE_FIELD(NPC_ENTER_FIELD, 1),
    NPC_ENTER_FIELD_FOR_QUICK_MOVE(NPC_ENTER_FIELD, 2),
    NPC_CHANGE_CONTROLLER(NPC_ENTER_FIELD, 3),

    // CNpcPool::OnNpcPacket : v176 -> 00CB4BF0
    NPC_MOVE(997),
    NPC_UPDATE_LIMITED_INFO(NPC_MOVE, 1),
    NPC_SET_QUIZ_SCORE(NPC_MOVE, 2),
    NPC_SET_QUIZ_SCORE_ANI(NPC_MOVE, 3),
    NPC_SET_FORCE_MOVE(NPC_MOVE, 4),
    NPC_SET_FORCE_FLIP(NPC_MOVE, 5),
    NPC_SET_EMOTION(NPC_MOVE, 6),
    NPC_SET_CHARACTER_BASE_ACTION(NPC_MOVE, 7),
    NPC_VIEW_OR_HIDE(NPC_MOVE, 8),
    NPC_PRESENT_ITEM_SET(NPC_MOVE, 9),
    NPC_PRESENT_TIME_SET(NPC_MOVE, 10),
    NPC_RESET_SPECIAL_ACTION(NPC_MOVE, 11),
    NPC_SET_SCREEN_INFO(NPC_MOVE, 12),
    NPC_LOCAL_NPC_REPEAT_EFFECT(NPC_MOVE, 13),
    NPC_SET_NOTICE_BOARD_INFO(NPC_MOVE, 14),
    NPC_SET_SPECIAL_ACTION(NPC_MOVE, 15),

    // CField_MomentSwimArea::OnPacket
    MOMENT_SWIM_AREA_SET_WATER_LEVEL(1019),

    // CEmployeePool::OnPacket
    EMPLOYEE_ENTER_FIELD(1017),
    EMPLOYEE_LEAVE_FIELD(EMPLOYEE_ENTER_FIELD, 1),
    EMPLOYEE_UNK(EMPLOYEE_ENTER_FIELD, 2),//int int
    EMPLOYEE_MINI_ROOM_BALLOON(EMPLOYEE_ENTER_FIELD, 3),

    // CDropPool::OnPacket
    DROP_ENTER_FIELD(1021),
    //null
    DROP_LEAVE_FIELD(DROP_ENTER_FIELD, 2),

    // CMessageBoxPool::OnPacket
    CREATE_MESSAGE_BOX_FAILED(1024),
    MESSAGE_BOX_ENTER_FIELD(CREATE_MESSAGE_BOX_FAILED, 1),
    MESSAGE_BOX_LEAVE_FIELD(CREATE_MESSAGE_BOX_FAILED, 2),

    // CAffectedAreaPool::OnPacket
    AFFECTED_AREA_CREATED(1027),
    INSTALLED_AREA_FIRE(AFFECTED_AREA_CREATED, 1),
    AFFECTED_AREA_REMOVED(AFFECTED_AREA_CREATED, 2),

    // CTownPortalPool::OnPacket
    TOWN_PORTAL_CREATED(1030),
    TOWN_PORTAL_REMOVED(TOWN_PORTAL_CREATED, 1),

    // CRandomPortalPool::OnPacket
    RANDOM_PORTAL_CREATED(1032),
    RANDOM_PORTAL_TRY_ENTER_REQUEST(RANDOM_PORTAL_CREATED, 1),
    RANDOM_PORTAL_REMOVED(RANDOM_PORTAL_CREATED, 2),

    // COpenGatePool::OnPacket
    OPEN_GATE_CREATED(1035),
    OPEN_GATE_CLOSE(OPEN_GATE_CREATED, 1),
    OPEN_GATE_REMOVED(OPEN_GATE_CREATED, 2),

    // CReactorPool::OnPacket
    REACTOR_CHANGE_STATE(1038),
    REACTOR_IDK(REACTOR_CHANGE_STATE, 1),
    REACTOR_ENTER_FIELD(REACTOR_CHANGE_STATE, 2),
    REACTOR_RESET_STATE(REACTOR_CHANGE_STATE, 3),
    REACTOR_OWNER_INFO(REACTOR_CHANGE_STATE, 4),
    REACTOR_REMOVE(REACTOR_CHANGE_STATE, 5),
    REACTOR_LEAVE_FIELD(REACTOR_CHANGE_STATE, 6),

    // CFishingZonePool::OnPacket
    FISHING_INFO(1045),
    FISHING_REWARD(FISHING_INFO, 1),
    FISHING_ZONE_INFO(FISHING_INFO, 2),

    DECOMPOSER_ENTER_FIELD(1048),
    DECOMPOSER_LEAVE_FIELD(DECOMPOSER_ENTER_FIELD, 1),

    // CField_SnowBall::OnPacket : v176 -> 00909DB0
    SnowBallState(1050),
    SnowBallHit(SnowBallState, 1),
    SnowBallMsg(SnowBallState, 2),
    SnowBallTouch(SnowBallState, 3),

    //CField_Coconut::OnPacket
    COCONUT_HIT(1054),
    COCONUT_SCORE(COCONUT_HIT, 1),

    // CField_GuildBoss::OnPacket
    GUILD_BOSS_HEALER_MOVE(1056),
    GUILD_BOSS_PULLEY_STATE_CHANGE(GUILD_BOSS_HEALER_MOVE, 1),

    // CField_MonsterCarnival::OnPacket
    MONSTER_CARNIVAL_CARNIVAL_ENTER(1058), // not a typo
    MONSTER_CARNIVAL_PERSONAL_CP(MONSTER_CARNIVAL_CARNIVAL_ENTER, 1),
    MONSTER_CARNIVAL_TEAM_CSCORE(MONSTER_CARNIVAL_CARNIVAL_ENTER, 2),
    MONSTER_CARNIVAL_SPELL_COOLTIME(MONSTER_CARNIVAL_CARNIVAL_ENTER, 3),
    MONSTER_CARNIVAL_RESULT_SUCCESS(MONSTER_CARNIVAL_CARNIVAL_ENTER, 4),
    MONSTER_CARNIVAL_RESULT_FAIL(MONSTER_CARNIVAL_CARNIVAL_ENTER, 5),
    MONSTER_CARNIVAL_DEATH(MONSTER_CARNIVAL_CARNIVAL_ENTER, 6),
    MONSTER_CARNIVAL_MEMBER_OUT(MONSTER_CARNIVAL_CARNIVAL_ENTER, 7),
    MONSTER_CARNIVAL_SHOW_GAME_RESULT(MONSTER_CARNIVAL_CARNIVAL_ENTER, 8),
    MONSTER_CARNIVAL_UPDATE_RANK_INFO(MONSTER_CARNIVAL_CARNIVAL_ENTER, 9),

    // CField_AriantArena::OnPacket
    ARIANT_ARENA_SHOW_RESULT(455),
    ARIANT_ARENA_USER_SCORE(1068),

    //+19

    // CField_Defense::OnPacket
    DEFENSE_WAVE(1087),
    DEFENSE_LIFE(DEFENSE_WAVE, 1),
    DEFENSE_POINT(DEFENSE_WAVE, 2),
    DEFENSE_SCORE_RANK(DEFENSE_WAVE, 3),
    DEFENSE_RESULT(DEFENSE_WAVE, 4),

    //+15

    // CField_MultiStage::OnPacket
    MULTI_STAGE_SET_STAGE(1106),
    MULTI_STAGE_SET_MONSTER_GAUGE(MULTI_STAGE_SET_STAGE, 1),

    // Kinda unplaced CField::OnPacket內
    FIELD_FADE_OBJECT_INFO(1167),
    RUNE_STONE_CLEAR_AND_ALL_REGISTER(1168),
    RUNE_STONE_DISAPPEAR(1169),
    RUNE_STONE_APPEAR(1170),
    //
    //
    //
    STAR_PLANET_SCREEN_WORLD_EVENT(1174),
    FIELD_STATE_CREATE(1175),
    FIELD_STATE_REMOVE(1176),
    CHASER_MOVE(1177),//更新到這

    COMPLETE_RUNE(1166),
    HORNTAIL_TIMER(1207),
    ZAKUM_TIMER(1211),
    ZAKUM_TIMER2(1280),
    TRUNK_DLG(1308),
    RPS_GAME_DLG(1311),
    GO_STOP_RPS_GAME_DLG(1312),
    STAR_PLANET_GO_STOP_RPS_DLG(1313),
    UI_MESSENGER(1314),
    MINI_ROOM_BASE_DLG(1315),
    SET_CASH_SHOP_INITIAL_ITEM(1316),
    TRY_MIGRATE_CASH_SHOP(1317),
    PARCEL_DLG(1339),

    //CField_LanguageSchool::OnPacket
    LanguageSchool_MESSAGE(1231),

    GIVE_SPECIAL_SKILL_BAR(1274), // Used for Skills in certain bosses, such as Demian

    // CScriptMan::OnPacket
    SCRIPT_MESSAGE(1324),

    // CShopDlg::OnPacket
    SHOP_OPEN(SCRIPT_MESSAGE, 1),
    SHOP_RESULT(SCRIPT_MESSAGE, 2),

    // CGachDlg::OnPacket
    GACH_OPEN(SCRIPT_MESSAGE, 3),
    GACH_RESULT(SCRIPT_MESSAGE, 4),

    //+7

    BEGIN_SOUL_DUNGEON(1335),
    SOUL_DUNGEON_SoulPiece_Change(1336),
    SOUL_DUNGEON_SoulItem_UseVoteRequest(SOUL_DUNGEON_SoulPiece_Change, 1),
    SOUL_DUNGEON_SoulItem_UseResult(SOUL_DUNGEON_SoulPiece_Change, 2),
    SOUL_DUNGEON_SoulItem_MapInfo(SOUL_DUNGEON_SoulPiece_Change, 3),
    SOUL_DUNGEON_SoulItem_MapInfo_Close(SOUL_DUNGEON_SoulPiece_Change, 4),
    SOUL_DUNGEON_SoulItem_DataChange(SOUL_DUNGEON_SoulPiece_Change, 5),
    SOUL_DUNGEON_SoulItem_VoteResult(SOUL_DUNGEON_SoulPiece_Change, 6),
    SOUL_DUNGEON_Effect(SOUL_DUNGEON_SoulPiece_Change, 7),
    SOUL_DUNGEON_MiniMapInfo(SOUL_DUNGEON_SoulPiece_Change, 8),
    END_SOUL_DUNGEON(SOUL_DUNGEON_SoulPiece_Change, 9),

    // Field_Coordy::OnPacket
    BEGIN_Coordination(1346),
    COORDINATION_RUNWAY_AVATAR(1347),
    END_Coordination(COORDINATION_RUNWAY_AVATAR, 1),

    // CStoreBankDlg::OnPacket
    STORE_BANK_GET_ALL_RESULT(1350),
    STORE_BANK_RESULT(),

    // CAdminShopDlg::OnPacket
    ADMIN_SHOP_RESULT(),
    ADMIN_SHOP_COMMODITY(),

    //CField_Tournament::OnPacket
    Tournament(1359),
    TournamentMatchTable(Tournament, 1),
    TournamentSetPrize(Tournament, 2),
    TournamentNoticeUEW(Tournament, 3),
    TournamentAvatarInfo(Tournament, 4),

    //CField_Wedding::OnPacket
    WeddingProgress(1364),
    WeddingCremonyEnd(WeddingProgress, 1),

    // CField_GhostPark::OnPacket
    BEGIN_GHOST_PARK_RUNE(1366),
    GHOST_PARK_RUNE_USE_ACK(1367),
    GHOST_PARK_RUNE_APPEAR(GHOST_PARK_RUNE_USE_ACK, 1),
    GHOST_PARK_RUNE_DISAPPEAR(GHOST_PARK_RUNE_USE_ACK, 2),
    GHOST_PARK_KILLED_MOB_BONUS_EXP_RATE_INFO(GHOST_PARK_RUNE_USE_ACK, 3),
    GHOST_PARK_CURSE_LEVEL_EXP_RATE(GHOST_PARK_RUNE_USE_ACK, 4),
    GHOST_PARK_HOMING_BULLET_CREATE(GHOST_PARK_RUNE_USE_ACK, 5),
    END_GHOST_PARK_RUNE(GHOST_PARK_RUNE_USE_ACK, 6),

    //+5

    //CField_Pachinko::OnPacket 1378~1380

    //+12

    // CCashShop::Init : v176 -> 01A1B510
    // CCashShop::OnPacket
    CASH_SHOP(1392),
    CASH_SHOP_QUERY_CASH_RESULT(CASH_SHOP, 1),
    CASH_SHOP_CASH_ITEM_RESULT(CASH_SHOP, 2),
    CASH_SHOP_PURCHASE_EXP_CHANGED(1343),
    CASH_SHOP_CHAR_STAT_CHANGED(1345),
    CASH_SHOP_IDK1(1347),
    CASH_SHOP_MVP_ITEM_GIVE_RESULT(1349), // probably
    CASH_SHOP_CHARGE_MILEAGE_NOTICE(1350),
    CASH_SHOP_IDK2(1352),
    CASH_SHOP_IDK3(1353),
    CASH_SHOP_IDK4(1355),
    CASH_SHOP_IDK5(1356),
    CASH_SHOP_IDK6(1357),
    CASH_SHOP_IDK7(1358),
    CASH_SHOP_IDK8(1359),
    CASH_SHOP_IDK9(1360),
    CASH_SHOP_IDK10(1363),
    CASH_SHOP_IDK11(1364),
    CASH_SHOP_INFO(1365), // In CClientSocket::ProcessPacket
    CASH_SHOP_ACTION(1366), // In CClientSocket::ProcessPacket
    CASH_SHOP_IDK12(1368),
    CASH_SHOP_IDK13(1370),
    CASH_SHOP_IDK14(1371),
    CASH_SHOP_IDK15(1372),

    //CStarPlanetInvitationMan::OnPacket
    StarPlanetInvitation_RunMatching(1465),
    StarPlanetInvitation_RegisterAck(StarPlanetInvitation_RunMatching, 1),
    StarPlanetInvitation_EndInvitation(StarPlanetInvitation_RunMatching, 2),

    // CFuncKeyMappedMan::OnPacket
    FUNC_KEY_MAPPED_MAN_INIT(1468),
    PET_CONSUME_ITEM_INIT(FUNC_KEY_MAPPED_MAN_INIT, 1),
    PET_CONSUME_MP_ITEM(FUNC_KEY_MAPPED_MAN_INIT, 2),
    PET_CONSUME_SKILL(FUNC_KEY_MAPPED_MAN_INIT, 3),

    // CUIGoldHammer::OnPacket
    GOLD_HAMMER_ITEM_UPGRADE_RESULT(1445),

    // CUIEgoEquip::OnPacket
    GAUGE_COMPLETE(1448),
    CREATE_UPGRADE_ITEM_COST_INFO(1449),
    CHECK_UPGRADE_ITEM_RESULT(1450),
    ITEM_UPGRADE_EFFECT(1451),

    // CFieldAttackObjPool::OnPacket
    FIELD_ATTACK_CREATE(1497),
    FIELD_ATTACK_REMOVE_BY_KEY(FIELD_ATTACK_CREATE, 1),
    FIELD_ATTACK_REMOVE_LIST(FIELD_ATTACK_CREATE, 2),
    FIELD_ATTACK_REMOVE_ALL(FIELD_ATTACK_CREATE, 3),
    //null
    //CFieldAttackObjPool::OnObjPacket
    FIELD_ATTACK_SET_ATTACK(1502),
    FIELD_ATTACK_RESULT_BOARD(FIELD_ATTACK_SET_ATTACK, 1),
    FIELD_ATTACK_RESULT_GET_OFF(FIELD_ATTACK_SET_ATTACK, 2),
    FIELD_ATTACK_PUSH_ACT(FIELD_ATTACK_SET_ATTACK, 3),
    FIELD_ATTACK_INFO(FIELD_ATTACK_SET_ATTACK, 4),

    // CBattleRecordMan::OnPacket
    DOT_DAMAGE_INFO(1512),
    KILL_DAMAGE_INFO(DOT_DAMAGE_INFO, 1),
    BATTLE_DAMAGE_INFO(DOT_DAMAGE_INFO, 2),
    SERVER_ON_CALC_REQUEST_RESULT(DOT_DAMAGE_INFO, 3),
    AGGRO_MONITORING_INFO(DOT_DAMAGE_INFO, 4),
    SKILL_DAMAGE_LOG(DOT_DAMAGE_INFO, 5),

    // CMonsterFarm::OnPacket : v176 -> 00C69BC6
    FARM_UPDATE_INVENTORY(1496),
    FARM_CONSOLE_MESSAGE(1497), // empty func in v176??
    FARM_OBJECT_INTERACT(1498),
    FARM_CONSUME_OBJECT(1499),
    FARM_DICTIONARY_RESULT(1500),
    FARM_UPDATE_BUY_OBJECT(1501),
    FARM_UPDATE_SELL_OBJECT(1502),
    FARM_COMBINE_RESULT(1503),
    FARM_MONSTER_SEARCH_RESULT(1504), // in KMST redirects to CUIFarmMatching::OnPacket
    FARM_VISIT_RESULT(1505),
    FARM_UPDATE_NEWS_FEED(1506),
    FARM_UPDATE_DICTIONARY(1507),
    FARM_AUTO_HARVEST_RESULT(1508),
    FARM_SOUL_RECHARGE_RESULT(1509),

    // CFarmUser::OnPacket : v176 -> 007FB400
    FARM_SET_USER(1512),
    FARM_SET_INVENTORY(1513),
    FARM_SET_QUEST_ALL(1514),
    FARM_QUEST_MESSAGE(1515),
    FARM_NOTICE_MESSAGE(1516),
    FARM_UPDATE_MONSTER_LIST(1517),
    FARM_UPDATE_DECO(1518),
    FARM_UPDATE_POINT(1519),
    FARM_UPDATE_CASH(1520),
    FARM_UPDATE_THEME(1521),
    FARM_UPDATE_MONSTER_SLOT(1522),
    FARM_UPDATE_MONSTER_LOCKER_SLOT(1523),
    FARM_UPDATE_EXP(1524),
    FARM_RESULT_CHECK_NAME(1525),
    FARM_RESULT_CHECK_NAME_BY_CONSUME(1526),
    FARM_RESULT_COMPLETE_QUEST(1527),
    FARM_RESULT_GET_USER_PHOTO(1528),
    FARM_RESULT_UPDATE_PHOTO(1529),
    FARM_RESULT_REFILL_DAILY_QUEST(1530),
    FARM_SEND_GIFT(1531),
    FARM_SET_FRIEND_LIST(1532),
    FARM_ONLINE_REFRESH(1533),
    FARM_RESULT_ADD_FRIEND(1534),
    FARM_RESULT_SEND_NOTICE(1535), // corrupted in my pdb :(
    FARM_RESULT_LOAD_MAIN_LOG(1536),
    FARM_RESULT_ADD_BLACKLIST(1537),
    FARM_RESULT_USER_INFO_UI(1538),
    FARM_SET_GUEST_OWNER_INFO(1539),
    FARM_WHISPER(1540),
    FARM_GROUP_MESSAGE(1541),
    FARM_BROADCAST_MSG(1542),
    FARM_NEW_LIST_RESULT(1543), // CFarmFriendRecommendMan::OnResultNewList
    FARM_SET_IN_GAME_INFO(1544),
    FARM_FORCED_SHOP_OPEN(1545),
    FARM_REQUEST_SET_IN_GAME_INFO(1546),
    // UNK 1547
    FARM_RESULT_IN_GAME_FRIEND_REQUEST(1548),
    FARM_IN_GAME_FRIEND_EVENT(1549),
    FARM_RESULT_WORLD_WHISPER(1550),
    FARM_TOTAL_INFO(1551), // CFarmStaticClientMan::OnTotalInfo

    // CField_Zakum::OnPacket : v176 -> 0092FB00
    FIELD_ZAKUM_DYNAMIC_OBJ_VISIBLE(463),
    FIELD_ZAKUM_SYNC_DYNAMIC_FOOTHOLD(FIELD_ZAKUM_DYNAMIC_OBJ_VISIBLE, 1),

    // CField_Urus::OnPacket : v176 -> 0092E230
    FIELD_URUS_DYNAMIC_OBJ_MOVE(462),
    FIELD_URUS_DYNAMIC_OBJ_VISIBLE(FIELD_URUS_DYNAMIC_OBJ_MOVE, 1),
    FIELD_URUS_SYNC_DYNAMIC_FOOTHOLD(FIELD_URUS_DYNAMIC_OBJ_MOVE, 2),

    // CField_SummonEvent::OnPacket : v176 -> 0091D220
    FIELD_SUMMONEVENT_EVENT_RANK(753),
    FIELD_SUMMONEVENT_EVENT_REWARD(FIELD_SUMMONEVENT_EVENT_RANK, 1),

    // CField_Witchtower::OnPacket : v176 -> 0092F770
    FIELD_WITCHTOWER_SCORE_UPDATE(1072),

    BossSummonTimer(1073),

    // CField_PvP::OnPacket

    // CField_BaseBallDrop::OnPacket : v176 -> 008E7320
    FIELD_BASEBALLDROP_ONPACKET(1092), // (*(this[-1].m_mPoint._Mysize + 208))(&this[-1].m_mPoint._Mysize, iPacket);
    //CField_RandomDrop::OnPacket
    FIELD_RANDOMDROP_OnSetPicked(FIELD_BASEBALLDROP_ONPACKET), // idk why this is the same as above -- (*(*this[-1].m_pBNSmall.gap0 + 204))(&this[-1].m_pBNSmall, iPacket);
    //
    //
    FIELD_RANDOMDROP_OnResult(FIELD_RANDOMDROP_OnSetPicked, 3), // (*(*this[-1].m_pBNSmall.gap0 + 208))(&this[-1].m_pBNSmall, iPacket);

    // CField_FlyingKiteDrop::OnPacket : V176 -> 008F1620
    FIELD_FLYINGKITEDROP_OnSetPicked(1093), // (this[-1].m_mPoint._Myhead[8]._Myval.second)(&this[-1].m_mPoint._Myhead, iPacket);
    FIELD_FLYINGKITEDROP_OnSetPhase(FIELD_FLYINGKITEDROP_OnSetPicked, 1), // single decode4 with a few pointer operations, not in a function in kmst
    //
    FIELD_FLYINGKITEDROP_POINT_EFFECT(FIELD_FLYINGKITEDROP_OnSetPicked, 3),

    // CField_PvPHardCore::OnPacket : v176 -> 008E71D0
    // todo :: op 1085 - 1093
    PvPHardCore_OnMigrate(),

    // CField_RhythmGame::OnPacket 1109 ~ 1120 1124

    // CField_MountainRiding::OnPacket : v176 -> 008EBA50
    MountainRidingHpInfo(1121),
    MountainRidingUIInfo(MountainRidingHpInfo, 1),
    MountainRidingMobInfo(MountainRidingHpInfo, 2),

    // CField_BossArena::OnPacket
    BOSS_ARENA_FIELD_STATE_CHANGE(1144),
    BOSS_ARENA_CURRENT_TEAM_INFO(BOSS_ARENA_FIELD_STATE_CHANGE, 1),
    BOSS_ARENA_SELECTED_TEAM_INFO(BOSS_ARENA_FIELD_STATE_CHANGE, 2),
    BOSS_ARENA_SELECT_OPPONENT_SELECT_BOSS(BOSS_ARENA_FIELD_STATE_CHANGE, 3),
    BOSS_ARENA_SELECT_OPPONENT_CONFIRM(BOSS_ARENA_FIELD_STATE_CHANGE, 4),

    // CField_Hekaton::OnPacket 包頭排列和魔王競技場混在一起
    HEKATON_OnDoHekatonSkill(BOSS_ARENA_FIELD_STATE_CHANGE, 5),
    HEKATON_OnReadySkill(BOSS_ARENA_FIELD_STATE_CHANGE, 6),
    HEKATON_OnRankingInfo(BOSS_ARENA_FIELD_STATE_CHANGE, 7),
    HEKATON_OnResult(BOSS_ARENA_FIELD_STATE_CHANGE, 8),
    BOSS_ARENA_SCORE(BOSS_ARENA_FIELD_STATE_CHANGE, 9),
    BOSS_ARENA_RESULT_INFO(BOSS_ARENA_FIELD_STATE_CHANGE, 10),
    HEKATON_OnUniverseBossHPInfo(BOSS_ARENA_FIELD_STATE_CHANGE, 11),
    BOSS_ARENA_FADE_IN_OUT(BOSS_ARENA_FIELD_STATE_CHANGE, 12),
    BOSS_ARENA_SUMMON_HEAD_GEAR(BOSS_ARENA_FIELD_STATE_CHANGE, 13),
    BOSS_ARENA_BOSS_INFO(BOSS_ARENA_FIELD_STATE_CHANGE, 14),
    BOSS_ARENA_USER_HP_CHANGED(BOSS_ARENA_FIELD_STATE_CHANGE, 15),//1159

    // CField_RunningGame::OnPacket : v176 -> 008FD3E0
    FIELD_RUNNINGGAME_MOB_INFO(MountainRidingMobInfo/*1123*/),
    // CField_RhythmGame::OnPacket
    FIELD_RHYTHMGAME_USER_NAME(1124),

    FIELD_ON_RANK_CREATE(1125),
    FIELD_RANK_SET_USERNAME(FIELD_ON_RANK_CREATE, 1),
    FIELD_RANK_NOTIFY_DATA(FIELD_ON_RANK_CREATE, 2),

    // CField_Piranha::OnPacket
    PIRANHA_INIT(1128),
    PIRANHA_ONOFF(PIRANHA_INIT, 1),
    PIRANHA_DIE(PIRANHA_INIT, 2),

    // CField_SpaceMoonRabbit::OnPacket : v176 -> 00912440
    // todo :: op 1160 ~ 1166

    //+5

    // CField_BonusReward::OnPacket
    BONUS_REWARD_BOARD_FAO(1171),

    //+7

    // CField_12th_Tresure::OnPacket
    TWELFTH_THREASURE_UPDATE_GAME_INFO(1178),
    TWELFTH_THREASURE_FIELD_STATE_CHANGE(TWELFTH_THREASURE_UPDATE_GAME_INFO, 1),

    // CField_PoloFritoBountyHunting::OnPacket : v176 -> 008D2B60
    FIELD_POLOFRITO_BOUNTYHUNTING_UPDATE_STAGE_INFO_UI(1180),

    // CField_PoloFritoTownDefense::OnPacket : v176 -> 008D66D0
    FIELD_POLOFRITO_TOWNDEFENSE_UPDATE_WAVE_INFO_UI(1181), // maybe shorten these names.. theyre kinda long ._.
    FIELD_POLOFRITO_TOWNDEFENSE_UPDATE_LINE_INFO_UI(FIELD_POLOFRITO_TOWNDEFENSE_UPDATE_WAVE_INFO_UI, 1),
    //CField_PoloFritoCourtshipDance::OnPacket
    PoloFritoCourtshipDanceState(1183),
    PoloFritoCourtshipDanceCommand(PoloFritoCourtshipDanceState, 1),

    // CField_RhythmGameJP::OnPacket 1185 ~ 1191

    // CField_DreamWorld::OnPacket 1192 1193

    // CField_Demian::OnPacket
    DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET(1194),
    DEMIAN_STIGMA_OBJECT_EFFECT(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 1),
    DEMIAN_FLYING_SWORD_CREATE(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 2),
    DEMIAN_FLYING_SWORD_MAKE_ENTER_REQUEST(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 3),
    DEMIAN_FLYING_SWORD_MAKE_ENTER_INFO(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 4),
    DEMIAN_FLYING_SWORD_NODE(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 5),
    DEMIAN_FLYING_SWORD_TARGET(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 6),
    DEMIAN_CORRUPTION_CHANGE(DEMIAN_STIGMA_INCINERATE_OBJECT_PACKET, 7),

    // CField_HundredBingo::OnPacket
    BINGO_ENTER_GAME(1202),
    BINGO_HOST_NUMBER(BINGO_ENTER_GAME, 1),
    BINGO_HOST_NUMBER_READY(BINGO_ENTER_GAME, 2),
    BINGO_ADD_RANK(BINGO_ENTER_GAME, 3),
    BINGO_REMOVE_RANK(BINGO_ENTER_GAME, 4),
    BINGO_FINISH_RANK(BINGO_ENTER_GAME, 5),
    BINGO_CHECK_NUMBER_ACK(BINGO_ENTER_GAME, 6),
    BINGO_GAME_STATE(BINGO_ENTER_GAME, 7),

    // CField_TypingGame::OnPacket : v176 -> 0092D7E0
    TypingGameWaveInfo(1210),
    TypingGameEnter(TypingGameWaveInfo, 1),
    TypingGameMoveToPortal(TypingGameWaveInfo, 2),
    TypingGameStart(TypingGameWaveInfo, 3),
    TypingGameResetWord(TypingGameWaveInfo, 4),
    TypingGameScore(TypingGameWaveInfo, 5),
    TypingGameResult(TypingGameWaveInfo, 6),
    TypingGameEffect(TypingGameWaveInfo, 7),
    TypingGameState(TypingGameWaveInfo, 8),
    TypingGamePointEffect(TypingGameWaveInfo, 9),
    TypingGameUserSkillAttack(TypingGameWaveInfo, 10),
    TypingGameSummon(TypingGameWaveInfo, 11),

    //CField_HundredOXQuiz::OnPacket
    HOxQuiz_STATE(1222),
    HOxQuiz_ENTER(HOxQuiz_STATE, 1),
    HOxQuiz_QUESTIONS(HOxQuiz_STATE, 2),
    HOxQuiz_EXPLAN(HOxQuiz_STATE, 3),
    HOxQuiz_COUNT_EFFECT(HOxQuiz_STATE, 4),
    HOxQuiz_MOVE_TO_PORTAL(HOxQuiz_STATE, 5),
    HOxQuiz_RESULT(HOxQuiz_STATE, 6),

    // CField_SideScrollFlyShooting : v176 -> 009077D0
    // todo :: op 1226 - 1232

    // CField_StarPlanetRps::OnPacket : V176 -> 009174B0
    // todo :: op 1219 - 1225

    // CField_Soul::OnPacket : v176 -> 0090B2F0
    // todo :: op 1295 - 1303

    SOCKET_CREATE_RESULT(1481),
    //CField_PhantomForest::OnPacket?
    GOLLUX_MINIMAP(1593),
    GOLLUX_PORTAL_OPEN(1569),
    ;

    private static final List<OutHeader> spam = Arrays.asList(
            ALIVE_REQ,
            PRIVATE_SERVER_PACKET_SEND,
            MOB_CONTROL_ACK,
            CHAT_MSG,
            MOB_HP_INDICATOR,
            STAT_CHANGED,
            MOB_CHANGE_CONTROLLER,
            MOB_MOVE,
            REMOTE_MOVE,
            REMOTE_EMOTION,
            EXCL_REQUEST,
            NPC_MOVE,
            DROP_LEAVE_FIELD,
            TEMPORARY_STAT_RESET,
            PET_MOVE,
            NPC_ENTER_FIELD,
            NPC_CHANGE_CONTROLLER,
            MOB_ENTER_FIELD,
            RESULT_INSTANCE_TABLE,
            CREATE_OBTACLE,
            DROP_ENTER_FIELD,
            MOB_LEAVE_FIELD,
            ANDROID_MOVE,
            MESSAGE
    );

    private final short value;

    OutHeader() {
        this(Counter.next);
    }

    OutHeader(int value) {
        this.value = (short) value;
        if (value != 0) {
            Counter.next = value + 1;
        }
    }

    OutHeader(OutHeader o, int offset) {
        this(o.value + offset);
    }

    OutHeader(OutHeader o) {
        this(o.value);
    }

    public short getValue() {
        return value;
    }

    public static OutHeader getOutHeaderByOp(int op) {
        return Arrays.stream(OutHeader.values()).filter(outHeader -> outHeader.getValue() == op).findFirst().orElse(null);
    }

    public static boolean isSpamHeader(OutHeader outHeader) {
        return spam.contains(outHeader);
    }

    private static class Counter {
        private static int next;
    }
}
